name: my_fbla
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  url_launcher: ^5.4.1
  flutter_launcher_icons: "^0.7.3"
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.1.1
  table_calendar: ^2.2.2
  firebase_database: ^3.1.1
  cupertino_icons: ^0.1.2
  qr_code_scanner: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/myFBLA.png"
  image_path_android: "assets/myFBLA.png"
  
flutter:
  uses-material-design: true

  assets:
   - assets/google_logo.png
   - assets/myFBLA.png